
- name: increase max_map_count
  command: sysctl -w vm.max_map_count=262144

- name: get docker
  command: docker pull docker.elastic.co/elasticsearch/elasticsearch:6.1.2

- name: deploy docker
  command: docker run -d -p 9200:9200 -p 9300:9300 docker.elastic.co/elasticsearch/elasticsearch:6.1.2

